export const client = {
  name: "Blue Sky Landscaping",
  tagline: "Professional landscaping services in Irvine",
  phone: "(949) 123-4567",
  email: "john@bluesky.com",
  address: "123 Main St",
  city: "Irvine",
  state: "CA",
  serviceArea: ["Irvine"],
  primaryColor: "#b45309",
  industry: "landscaping",
  services: ["Lawn care","Garden design","Irrigation","Tree trimming","Mulching","Sod installation","Leaf removal"],
  cmsUrl: "https://cms.sebvia.com",
  tenantSlug: "blue-sky-landscaping",
  googleAnalyticsId: '',
  domain: "bluesky.sebvia.com",
};
